import type { UpdateRecord, BuildRecord, AuditLogRecord, WebhookRecord, BranchRecord, ChannelRecord, AdoptionResponse } from './client'

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(d.getHours() - Math.floor(Math.random() * 12))
  return d.toISOString()
}

function uuid(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0
    const v = c === 'x' ? r : (r & 0x3) | 0x8
    return v.toString(16)
  })
}

function sha(): string {
  return Array.from({ length: 40 }, () =>
    Math.floor(Math.random() * 16).toString(16)
  ).join('')
}

export const mockUpdates: UpdateRecord[] = [
  {
    id: 1,
    runtimeVersion: '2.4.1',
    platform: 'ios',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 100,
    isCritical: false,
    isEnabled: true,
    releaseMessage: 'Fix crash on login screen for iOS 18 users',
    expoConfig: {},
    createdAt: daysAgo(0),
    assetCount: 12,
    totalSize: 524288,
    groupId: 'grp-001',
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 4823,
    uniqueDevices: 1247,
    runtimeFingerprint: 'abc123def456',
    gitCommitHash: sha(),
    gitBranch: 'main',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12200',
    buildMessage: 'Fix crash on login screen for iOS 18 users',
  },
  {
    id: 2,
    runtimeVersion: '2.4.1',
    platform: 'android',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 50,
    isCritical: false,
    isEnabled: true,
    releaseMessage: 'Fix crash on login screen for iOS 18 users',
    expoConfig: {},
    createdAt: daysAgo(1),
    assetCount: 14,
    totalSize: 1048576,
    groupId: 'grp-001',
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 2156,
    uniqueDevices: 893,
    runtimeFingerprint: 'abc123def456',
    gitCommitHash: sha(),
    gitBranch: 'main',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12201',
    buildMessage: 'Fix crash on login screen for iOS 18 users',
  },
  {
    id: 3,
    runtimeVersion: '2.4.0',
    platform: 'ios',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 100,
    isCritical: true,
    isEnabled: true,
    releaseMessage: 'Critical: Fix payment processing double-charge bug',
    expoConfig: {},
    createdAt: daysAgo(3),
    assetCount: 18,
    totalSize: 2097152,
    groupId: 'grp-002',
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 312,
    uniqueDevices: 45,
    runtimeFingerprint: 'xyz789ghi012',
    gitCommitHash: sha(),
    gitBranch: 'fix/payment-bug',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12150',
    buildMessage: 'Critical: Fix payment processing double-charge bug',
  },
  {
    id: 4,
    runtimeVersion: '2.4.0',
    platform: 'android',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 100,
    isCritical: true,
    isEnabled: true,
    releaseMessage: 'Critical: Fix payment processing double-charge bug',
    expoConfig: {},
    createdAt: daysAgo(5),
    assetCount: 11,
    totalSize: 786432,
    groupId: 'grp-002',
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 18430,
    uniqueDevices: 6102,
    runtimeFingerprint: 'xyz789ghi012',
    gitCommitHash: sha(),
    gitBranch: 'fix/payment-bug',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12151',
    buildMessage: 'Critical: Fix payment processing double-charge bug',
  },
  {
    id: 5,
    runtimeVersion: '2.3.9',
    platform: 'ios',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'canary',
    rolloutPercentage: 10,
    isCritical: false,
    isEnabled: true,
    releaseMessage: 'Experimental: New navigation architecture',
    expoConfig: {},
    createdAt: daysAgo(8),
    assetCount: 22,
    totalSize: 3145728,
    groupId: null,
    rollbackToUpdateId: null,
    branchName: 'canary',
    totalDownloads: 87,
    uniqueDevices: 23,
    runtimeFingerprint: 'nav-arch-001',
    gitCommitHash: sha(),
    gitBranch: 'feat/new-nav',
    ciRunUrl: null,
    buildMessage: 'Experimental: New navigation architecture',
  },
  {
    id: 6,
    runtimeVersion: '2.3.8',
    platform: 'ios',
    updateUuid: uuid(),
    isRollback: true,
    channel: 'production',
    rolloutPercentage: 100,
    isCritical: false,
    isEnabled: true,
    releaseMessage: 'Rollback: Reverting broken push notification handler',
    expoConfig: {},
    createdAt: daysAgo(12),
    assetCount: 0,
    totalSize: 0,
    groupId: null,
    rollbackToUpdateId: 7,
    branchName: 'main',
    totalDownloads: 9210,
    uniqueDevices: 3841,
    runtimeFingerprint: null,
    gitCommitHash: null,
    gitBranch: null,
    ciRunUrl: null,
    buildMessage: null,
  },
  {
    id: 7,
    runtimeVersion: '2.3.7',
    platform: 'android',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 100,
    isCritical: false,
    isEnabled: false,
    releaseMessage: 'Performance optimizations for list rendering',
    expoConfig: {},
    createdAt: daysAgo(18),
    assetCount: 9,
    totalSize: 655360,
    groupId: 'grp-003',
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 15200,
    uniqueDevices: 5430,
    runtimeFingerprint: 'perf-opt-v1',
    gitCommitHash: sha(),
    gitBranch: 'perf/list-rendering',
    ciRunUrl: 'https://github.com/example/app/actions/runs/11900',
    buildMessage: 'Performance optimizations for list rendering',
  },
  {
    id: 8,
    runtimeVersion: '2.3.7',
    platform: 'ios',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 25,
    isCritical: false,
    isEnabled: true,
    releaseMessage: 'Performance optimizations for list rendering',
    expoConfig: {},
    createdAt: daysAgo(22),
    assetCount: 16,
    totalSize: 1572864,
    groupId: 'grp-003',
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 1340,
    uniqueDevices: 502,
    runtimeFingerprint: 'perf-opt-v1',
    gitCommitHash: sha(),
    gitBranch: 'perf/list-rendering',
    ciRunUrl: 'https://github.com/example/app/actions/runs/11901',
    buildMessage: 'Performance optimizations for list rendering',
  },
  {
    id: 9,
    runtimeVersion: '2.3.5',
    platform: 'android',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'staging',
    rolloutPercentage: 100,
    isCritical: false,
    isEnabled: false,
    releaseMessage: 'Refactored analytics event tracking',
    expoConfig: {},
    createdAt: daysAgo(30),
    assetCount: 10,
    totalSize: 892416,
    groupId: null,
    rollbackToUpdateId: null,
    branchName: 'staging',
    totalDownloads: 560,
    uniqueDevices: 82,
    runtimeFingerprint: 'analytics-v2',
    gitCommitHash: sha(),
    gitBranch: 'refactor/analytics',
    ciRunUrl: null,
    buildMessage: 'Refactored analytics event tracking',
  },
  {
    id: 10,
    runtimeVersion: '2.3.4',
    platform: 'ios',
    updateUuid: uuid(),
    isRollback: false,
    channel: 'production',
    rolloutPercentage: 100,
    isCritical: false,
    isEnabled: true,
    releaseMessage: 'Updated translations for 12 languages',
    expoConfig: {},
    createdAt: daysAgo(45),
    assetCount: 8,
    totalSize: 458752,
    groupId: null,
    rollbackToUpdateId: null,
    branchName: 'main',
    totalDownloads: 22100,
    uniqueDevices: 8901,
    runtimeFingerprint: 'i18n-v3',
    gitCommitHash: sha(),
    gitBranch: 'main',
    ciRunUrl: 'https://github.com/example/app/actions/runs/11500',
    buildMessage: 'Updated translations for 12 languages',
  },
]

export const mockBuilds: BuildRecord[] = [
  {
    id: 1,
    buildUuid: uuid(),
    runtimeVersion: '2.5.0',
    platform: 'ios',
    gitCommitHash: sha(),
    gitBranch: 'feat/push-notifications-v2',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12345',
    message: 'Redesigned push notification preferences screen',
    createdAt: daysAgo(0),
    assetCount: 15,
    isPublished: false,
  },
  {
    id: 2,
    buildUuid: uuid(),
    runtimeVersion: '2.5.0',
    platform: 'android',
    gitCommitHash: sha(),
    gitBranch: 'feat/push-notifications-v2',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12346',
    message: 'Redesigned push notification preferences screen',
    createdAt: daysAgo(0),
    assetCount: 15,
    isPublished: false,
  },
  {
    id: 3,
    buildUuid: uuid(),
    runtimeVersion: '2.4.2',
    platform: 'ios',
    gitCommitHash: sha(),
    gitBranch: 'fix/deep-linking',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12300',
    message: 'Fix deep link handling for universal links',
    createdAt: daysAgo(1),
    assetCount: 12,
    isPublished: false,
  },
  {
    id: 4,
    buildUuid: uuid(),
    runtimeVersion: '2.4.1',
    platform: 'ios',
    gitCommitHash: sha(),
    gitBranch: 'main',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12200',
    message: 'Fix crash on login screen for iOS 18 users',
    createdAt: daysAgo(2),
    assetCount: 12,
    isPublished: true,
  },
  {
    id: 5,
    buildUuid: uuid(),
    runtimeVersion: '2.4.1',
    platform: 'android',
    gitCommitHash: sha(),
    gitBranch: 'main',
    ciRunUrl: 'https://github.com/example/app/actions/runs/12201',
    message: 'New checkout flow with Apple Pay integration',
    createdAt: daysAgo(2),
    assetCount: 14,
    isPublished: true,
  },
  {
    id: 6,
    buildUuid: uuid(),
    runtimeVersion: '2.4.0',
    platform: 'android',
    gitCommitHash: sha(),
    gitBranch: 'release/2.4.0',
    ciRunUrl: null,
    message: 'Release 2.4.0 build',
    createdAt: daysAgo(6),
    assetCount: 11,
    isPublished: true,
  },
]

export const mockAuditLog: AuditLogRecord[] = [
  {
    id: 1,
    action: 'build.uploaded',
    entityType: 'build',
    entityId: 1,
    details: { runtimeVersion: '2.5.0', platform: 'ios', gitBranch: 'feat/push-notifications-v2' },
    createdAt: daysAgo(0),
    actorType: 'api_key',
    actorName: 'CI/CD Pipeline',
  },
  {
    id: 2,
    action: 'build.uploaded',
    entityType: 'build',
    entityId: 2,
    details: { runtimeVersion: '2.5.0', platform: 'android', gitBranch: 'feat/push-notifications-v2' },
    createdAt: daysAgo(0),
    actorType: 'api_key',
    actorName: 'CI/CD Pipeline',
  },
  {
    id: 3,
    action: 'build.published',
    entityType: 'build',
    entityId: 4,
    details: { updateId: 1, channel: 'production', rolloutPercentage: 100, runtimeVersion: '2.4.1', platform: 'ios' },
    createdAt: daysAgo(0),
    actorType: 'api_key',
    actorName: 'CI/CD Pipeline',
  },
  {
    id: 4,
    action: 'update.patched',
    entityType: 'update',
    entityId: 2,
    details: { rolloutPercentage: 50, isEnabled: null, isCritical: null },
    createdAt: daysAgo(1),
    actorType: 'user',
    actorName: 'Alex',
  },
  {
    id: 5,
    action: 'build.published',
    entityType: 'build',
    entityId: 5,
    details: { updateId: 2, channel: 'production', rolloutPercentage: 50, runtimeVersion: '2.4.1', platform: 'android' },
    createdAt: daysAgo(1),
    actorType: 'user',
    actorName: 'Alex',
  },
  {
    id: 6,
    action: 'update.patched',
    entityType: 'update',
    entityId: 4,
    details: { isCritical: true, rolloutPercentage: null, isEnabled: null },
    createdAt: daysAgo(5),
    actorType: 'user',
    actorName: 'Alex',
  },
  {
    id: 7,
    action: 'webhook.created',
    entityType: 'webhook',
    entityId: 1,
    details: { url: 'https://hooks.slack.com/services/T00/B00/xxx', events: ['build.uploaded', 'build.published'] },
    createdAt: daysAgo(10),
    actorType: 'user',
    actorName: 'Alex',
  },
  {
    id: 8,
    action: 'update.patched',
    entityType: 'update',
    entityId: 7,
    details: { isEnabled: false, rolloutPercentage: null, isCritical: null },
    createdAt: daysAgo(18),
    actorType: 'user',
    actorName: 'Alex',
  },
  {
    id: 9,
    action: 'build.uploaded',
    entityType: 'build',
    entityId: 6,
    details: { runtimeVersion: '2.4.0', platform: 'android', gitBranch: 'release/2.4.0' },
    createdAt: daysAgo(6),
    actorType: 'api_key',
    actorName: 'CI/CD Pipeline',
  },
  {
    id: 10,
    action: 'build.published',
    entityType: 'build',
    entityId: 6,
    details: { updateId: 4, channel: 'production', rolloutPercentage: 100, runtimeVersion: '2.4.0', platform: 'android' },
    createdAt: daysAgo(5),
    actorType: 'api_key',
    actorName: 'CI/CD Pipeline',
  },
]

export const mockBranches: BranchRecord[] = [
  { id: 1, name: 'main', createdAt: daysAgo(90) },
  { id: 2, name: 'staging', createdAt: daysAgo(90) },
  { id: 3, name: 'canary', createdAt: daysAgo(60) },
  { id: 4, name: 'hotfix/payment', createdAt: daysAgo(5) },
]

export const mockChannels: ChannelRecord[] = [
  { name: 'production', branchName: 'main', rolloutBranchName: null, rolloutPercentage: 0, createdAt: daysAgo(90), minRuntimeVersion: null },
  { name: 'staging', branchName: 'staging', rolloutBranchName: null, rolloutPercentage: 0, createdAt: daysAgo(90), minRuntimeVersion: null },
  { name: 'canary', branchName: 'canary', rolloutBranchName: 'main', rolloutPercentage: 25, createdAt: daysAgo(60), minRuntimeVersion: null },
]

function generateAdoptionTimeseries(totalDays = 90): AdoptionResponse['timeseries'] {
  const buckets: AdoptionResponse['timeseries'] = []
  const updateIds = [1, 2, 3, 4]
  for (let day = totalDays - 1; day >= 0; day--) {
    const d = new Date()
    d.setDate(d.getDate() - day)
    d.setHours(0, 0, 0, 0)
    for (const uid of updateIds) {
      const age = totalDays - day
      let downloads: number
      if (uid <= 2) {
        const peak = 600
        downloads = Math.floor(peak * Math.pow(age / totalDays, 2) + Math.random() * 80)
      } else if (uid === 3) {
        const peak = 400
        const mid = totalDays / 2
        downloads = Math.floor(peak * Math.exp(-0.5 * Math.pow((age - mid) / (totalDays / 4), 2)) + Math.random() * 50)
      } else {
        downloads = Math.floor(300 * Math.exp(-age * 0.03) + Math.random() * 30)
      }
      buckets.push({
        bucketTime: d.toISOString(),
        updateId: uid,
        downloads: Math.max(5, downloads),
        uniqueDevices: Math.max(2, Math.floor(downloads * 0.6 + Math.random() * 10)),
      })
    }
  }
  return buckets
}

export const mockAdoption: AdoptionResponse = {
  timeseries: generateAdoptionTimeseries(),
  currentAdoption: [
    { updateId: 1, updateUuid: uuid(), runtimeVersion: '2.4.1', channel: 'production', branchName: 'main', deviceCount: 4230 },
    { updateId: 2, updateUuid: uuid(), runtimeVersion: '2.4.1', channel: 'production', branchName: 'main', deviceCount: 3180 },
    { updateId: 4, updateUuid: uuid(), runtimeVersion: '2.4.0', channel: 'production', branchName: 'main', deviceCount: 2850 },
    { updateId: 3, updateUuid: uuid(), runtimeVersion: '2.4.0', channel: 'production', branchName: 'main', deviceCount: 1920 },
    { updateId: 10, updateUuid: uuid(), runtimeVersion: '2.3.4', channel: 'production', branchName: 'main', deviceCount: 890 },
    { updateId: 8, updateUuid: uuid(), runtimeVersion: '2.3.7', channel: 'production', branchName: 'main', deviceCount: 502 },
    { updateId: 5, updateUuid: uuid(), runtimeVersion: '2.3.9', channel: 'canary', branchName: 'canary', deviceCount: 23 },
  ],
}

export const mockWebhooks: WebhookRecord[] = [
  {
    id: 1,
    url: 'https://hooks.slack.com/services/T00/B00/xxx',
    events: ['build.uploaded', 'build.published'],
    isActive: true,
    secret: null,
    createdAt: daysAgo(10),
  },
  {
    id: 2,
    url: 'https://api.example.com/webhooks/ota',
    events: ['build.uploaded', 'build.published', 'update.created', 'update.patched'],
    isActive: false,
    secret: 'whsec_abc123',
    createdAt: daysAgo(30),
  },
]
