import type { UpdateRecord, BuildRecord, AuditLogRecord, WebhookRecord, BranchRecord, ChannelRecord, AdoptionResponse } from './client'

function daysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(d.getHours() - Math.floor(Math.random() * 12))
  return d.toISOString()
}

function uuid(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0
    const v = c === 'x' ? r : (r & 0x3) | 0x8
    return v.toString(16)
  })
}

function sha(): string {
  return Array.from({ length: 40 }, () =>
    Math.floor(Math.random() * 16).toString(16)
  ).join('')
}

export const mockUpdates: UpdateRecord[] = [
  {
    id: 1,
    runtime_version: '2.4.1',
    platform: 'ios',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 100,
    is_critical: false,
    is_enabled: true,
    release_message: 'Fix crash on login screen for iOS 18 users',
    expo_config: {},
    created_at: daysAgo(0),
    asset_count: 12,
    total_size: 524288,
    group_id: 'grp-001',
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 4823,
    unique_devices: 1247,
    runtime_fingerprint: 'abc123def456',
    git_commit_hash: sha(),
    git_branch: 'main',
    ci_run_url: 'https://github.com/example/app/actions/runs/12200',
    build_message: 'Fix crash on login screen for iOS 18 users',
  },
  {
    id: 2,
    runtime_version: '2.4.1',
    platform: 'android',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 50,
    is_critical: false,
    is_enabled: true,
    release_message: 'Fix crash on login screen for iOS 18 users',
    expo_config: {},
    created_at: daysAgo(1),
    asset_count: 14,
    total_size: 1048576,
    group_id: 'grp-001',
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 2156,
    unique_devices: 893,
    runtime_fingerprint: 'abc123def456',
    git_commit_hash: sha(),
    git_branch: 'main',
    ci_run_url: 'https://github.com/example/app/actions/runs/12201',
    build_message: 'Fix crash on login screen for iOS 18 users',
  },
  {
    id: 3,
    runtime_version: '2.4.0',
    platform: 'ios',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 100,
    is_critical: true,
    is_enabled: true,
    release_message: 'Critical: Fix payment processing double-charge bug',
    expo_config: {},
    created_at: daysAgo(3),
    asset_count: 18,
    total_size: 2097152,
    group_id: 'grp-002',
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 312,
    unique_devices: 45,
    runtime_fingerprint: 'xyz789ghi012',
    git_commit_hash: sha(),
    git_branch: 'fix/payment-bug',
    ci_run_url: 'https://github.com/example/app/actions/runs/12150',
    build_message: 'Critical: Fix payment processing double-charge bug',
  },
  {
    id: 4,
    runtime_version: '2.4.0',
    platform: 'android',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 100,
    is_critical: true,
    is_enabled: true,
    release_message: 'Critical: Fix payment processing double-charge bug',
    expo_config: {},
    created_at: daysAgo(5),
    asset_count: 11,
    total_size: 786432,
    group_id: 'grp-002',
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 18430,
    unique_devices: 6102,
    runtime_fingerprint: 'xyz789ghi012',
    git_commit_hash: sha(),
    git_branch: 'fix/payment-bug',
    ci_run_url: 'https://github.com/example/app/actions/runs/12151',
    build_message: 'Critical: Fix payment processing double-charge bug',
  },
  {
    id: 5,
    runtime_version: '2.3.9',
    platform: 'ios',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'canary',
    rollout_percentage: 10,
    is_critical: false,
    is_enabled: true,
    release_message: 'Experimental: New navigation architecture',
    expo_config: {},
    created_at: daysAgo(8),
    asset_count: 22,
    total_size: 3145728,
    group_id: null,
    rollback_to_update_id: null,
    branch_name: 'canary',
    total_downloads: 87,
    unique_devices: 23,
    runtime_fingerprint: 'nav-arch-001',
    git_commit_hash: sha(),
    git_branch: 'feat/new-nav',
    ci_run_url: null,
    build_message: 'Experimental: New navigation architecture',
  },
  {
    id: 6,
    runtime_version: '2.3.8',
    platform: 'ios',
    update_uuid: uuid(),
    is_rollback: true,
    channel: 'production',
    rollout_percentage: 100,
    is_critical: false,
    is_enabled: true,
    release_message: 'Rollback: Reverting broken push notification handler',
    expo_config: {},
    created_at: daysAgo(12),
    asset_count: 0,
    total_size: 0,
    group_id: null,
    rollback_to_update_id: 7,
    branch_name: 'main',
    total_downloads: 9210,
    unique_devices: 3841,
    runtime_fingerprint: null,
    git_commit_hash: null,
    git_branch: null,
    ci_run_url: null,
    build_message: null,
  },
  {
    id: 7,
    runtime_version: '2.3.7',
    platform: 'android',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 100,
    is_critical: false,
    is_enabled: false,
    release_message: 'Performance optimizations for list rendering',
    expo_config: {},
    created_at: daysAgo(18),
    asset_count: 9,
    total_size: 655360,
    group_id: 'grp-003',
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 15200,
    unique_devices: 5430,
    runtime_fingerprint: 'perf-opt-v1',
    git_commit_hash: sha(),
    git_branch: 'perf/list-rendering',
    ci_run_url: 'https://github.com/example/app/actions/runs/11900',
    build_message: 'Performance optimizations for list rendering',
  },
  {
    id: 8,
    runtime_version: '2.3.7',
    platform: 'ios',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 25,
    is_critical: false,
    is_enabled: true,
    release_message: 'Performance optimizations for list rendering',
    expo_config: {},
    created_at: daysAgo(22),
    asset_count: 16,
    total_size: 1572864,
    group_id: 'grp-003',
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 1340,
    unique_devices: 502,
    runtime_fingerprint: 'perf-opt-v1',
    git_commit_hash: sha(),
    git_branch: 'perf/list-rendering',
    ci_run_url: 'https://github.com/example/app/actions/runs/11901',
    build_message: 'Performance optimizations for list rendering',
  },
  {
    id: 9,
    runtime_version: '2.3.5',
    platform: 'android',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'staging',
    rollout_percentage: 100,
    is_critical: false,
    is_enabled: false,
    release_message: 'Refactored analytics event tracking',
    expo_config: {},
    created_at: daysAgo(30),
    asset_count: 10,
    total_size: 892416,
    group_id: null,
    rollback_to_update_id: null,
    branch_name: 'staging',
    total_downloads: 560,
    unique_devices: 82,
    runtime_fingerprint: 'analytics-v2',
    git_commit_hash: sha(),
    git_branch: 'refactor/analytics',
    ci_run_url: null,
    build_message: 'Refactored analytics event tracking',
  },
  {
    id: 10,
    runtime_version: '2.3.4',
    platform: 'ios',
    update_uuid: uuid(),
    is_rollback: false,
    channel: 'production',
    rollout_percentage: 100,
    is_critical: false,
    is_enabled: true,
    release_message: 'Updated translations for 12 languages',
    expo_config: {},
    created_at: daysAgo(45),
    asset_count: 8,
    total_size: 458752,
    group_id: null,
    rollback_to_update_id: null,
    branch_name: 'main',
    total_downloads: 22100,
    unique_devices: 8901,
    runtime_fingerprint: 'i18n-v3',
    git_commit_hash: sha(),
    git_branch: 'main',
    ci_run_url: 'https://github.com/example/app/actions/runs/11500',
    build_message: 'Updated translations for 12 languages',
  },
]

export const mockBuilds: BuildRecord[] = [
  {
    id: 1,
    build_uuid: uuid(),
    runtime_version: '2.5.0',
    platform: 'ios',
    git_commit_hash: sha(),
    git_branch: 'feat/push-notifications-v2',
    ci_run_url: 'https://github.com/example/app/actions/runs/12345',
    message: 'Redesigned push notification preferences screen',
    created_at: daysAgo(0),
    asset_count: 15,
    is_published: false,
  },
  {
    id: 2,
    build_uuid: uuid(),
    runtime_version: '2.5.0',
    platform: 'android',
    git_commit_hash: sha(),
    git_branch: 'feat/push-notifications-v2',
    ci_run_url: 'https://github.com/example/app/actions/runs/12346',
    message: 'Redesigned push notification preferences screen',
    created_at: daysAgo(0),
    asset_count: 15,
    is_published: false,
  },
  {
    id: 3,
    build_uuid: uuid(),
    runtime_version: '2.4.2',
    platform: 'ios',
    git_commit_hash: sha(),
    git_branch: 'fix/deep-linking',
    ci_run_url: 'https://github.com/example/app/actions/runs/12300',
    message: 'Fix deep link handling for universal links',
    created_at: daysAgo(1),
    asset_count: 12,
    is_published: false,
  },
  {
    id: 4,
    build_uuid: uuid(),
    runtime_version: '2.4.1',
    platform: 'ios',
    git_commit_hash: sha(),
    git_branch: 'main',
    ci_run_url: 'https://github.com/example/app/actions/runs/12200',
    message: 'Fix crash on login screen for iOS 18 users',
    created_at: daysAgo(2),
    asset_count: 12,
    is_published: true,
  },
  {
    id: 5,
    build_uuid: uuid(),
    runtime_version: '2.4.1',
    platform: 'android',
    git_commit_hash: sha(),
    git_branch: 'main',
    ci_run_url: 'https://github.com/example/app/actions/runs/12201',
    message: 'New checkout flow with Apple Pay integration',
    created_at: daysAgo(2),
    asset_count: 14,
    is_published: true,
  },
  {
    id: 6,
    build_uuid: uuid(),
    runtime_version: '2.4.0',
    platform: 'android',
    git_commit_hash: sha(),
    git_branch: 'release/2.4.0',
    ci_run_url: null,
    message: 'Release 2.4.0 build',
    created_at: daysAgo(6),
    asset_count: 11,
    is_published: true,
  },
]

export const mockAuditLog: AuditLogRecord[] = [
  {
    id: 1,
    action: 'build.uploaded',
    entity_type: 'build',
    entity_id: 1,
    details: { runtime_version: '2.5.0', platform: 'ios', git_branch: 'feat/push-notifications-v2' },
    created_at: daysAgo(0),
    actor_type: 'api_key',
    actor_name: 'CI/CD Pipeline',
  },
  {
    id: 2,
    action: 'build.uploaded',
    entity_type: 'build',
    entity_id: 2,
    details: { runtime_version: '2.5.0', platform: 'android', git_branch: 'feat/push-notifications-v2' },
    created_at: daysAgo(0),
    actor_type: 'api_key',
    actor_name: 'CI/CD Pipeline',
  },
  {
    id: 3,
    action: 'build.published',
    entity_type: 'build',
    entity_id: 4,
    details: { update_id: 1, channel: 'production', rollout_percentage: 100, runtime_version: '2.4.1', platform: 'ios' },
    created_at: daysAgo(0),
    actor_type: 'api_key',
    actor_name: 'CI/CD Pipeline',
  },
  {
    id: 4,
    action: 'update.patched',
    entity_type: 'update',
    entity_id: 2,
    details: { rollout_percentage: 50, is_enabled: null, is_critical: null },
    created_at: daysAgo(1),
    actor_type: 'user',
    actor_name: 'Alex',
  },
  {
    id: 5,
    action: 'build.published',
    entity_type: 'build',
    entity_id: 5,
    details: { update_id: 2, channel: 'production', rollout_percentage: 50, runtime_version: '2.4.1', platform: 'android' },
    created_at: daysAgo(1),
    actor_type: 'user',
    actor_name: 'Alex',
  },
  {
    id: 6,
    action: 'update.patched',
    entity_type: 'update',
    entity_id: 4,
    details: { is_critical: true, rollout_percentage: null, is_enabled: null },
    created_at: daysAgo(5),
    actor_type: 'user',
    actor_name: 'Alex',
  },
  {
    id: 7,
    action: 'webhook.created',
    entity_type: 'webhook',
    entity_id: 1,
    details: { url: 'https://hooks.slack.com/services/T00/B00/xxx', events: ['build.uploaded', 'build.published'] },
    created_at: daysAgo(10),
    actor_type: 'user',
    actor_name: 'Alex',
  },
  {
    id: 8,
    action: 'update.patched',
    entity_type: 'update',
    entity_id: 7,
    details: { is_enabled: false, rollout_percentage: null, is_critical: null },
    created_at: daysAgo(18),
    actor_type: 'user',
    actor_name: 'Alex',
  },
  {
    id: 9,
    action: 'build.uploaded',
    entity_type: 'build',
    entity_id: 6,
    details: { runtime_version: '2.4.0', platform: 'android', git_branch: 'release/2.4.0' },
    created_at: daysAgo(6),
    actor_type: 'api_key',
    actor_name: 'CI/CD Pipeline',
  },
  {
    id: 10,
    action: 'build.published',
    entity_type: 'build',
    entity_id: 6,
    details: { update_id: 4, channel: 'production', rollout_percentage: 100, runtime_version: '2.4.0', platform: 'android' },
    created_at: daysAgo(5),
    actor_type: 'api_key',
    actor_name: 'CI/CD Pipeline',
  },
]

export const mockBranches: BranchRecord[] = [
  { id: 1, name: 'main', created_at: daysAgo(90) },
  { id: 2, name: 'staging', created_at: daysAgo(90) },
  { id: 3, name: 'canary', created_at: daysAgo(60) },
  { id: 4, name: 'hotfix/payment', created_at: daysAgo(5) },
]

export const mockChannels: ChannelRecord[] = [
  { name: 'production', branchName: 'main', rolloutBranchName: null, rolloutPercentage: 0, createdAt: daysAgo(90), minRuntimeVersion: null },
  { name: 'staging', branchName: 'staging', rolloutBranchName: null, rolloutPercentage: 0, createdAt: daysAgo(90), minRuntimeVersion: null },
  { name: 'canary', branchName: 'canary', rolloutBranchName: 'main', rolloutPercentage: 25, createdAt: daysAgo(60), minRuntimeVersion: null },
]

function generateAdoptionTimeseries(totalDays = 90): AdoptionResponse['timeseries'] {
  const buckets: AdoptionResponse['timeseries'] = []
  const updateIds = [1, 2, 3, 4]
  for (let day = totalDays - 1; day >= 0; day--) {
    const d = new Date()
    d.setDate(d.getDate() - day)
    d.setHours(0, 0, 0, 0)
    for (const uid of updateIds) {
      const age = totalDays - day
      let downloads: number
      if (uid <= 2) {
        const peak = 600
        downloads = Math.floor(peak * Math.pow(age / totalDays, 2) + Math.random() * 80)
      } else if (uid === 3) {
        const peak = 400
        const mid = totalDays / 2
        downloads = Math.floor(peak * Math.exp(-0.5 * Math.pow((age - mid) / (totalDays / 4), 2)) + Math.random() * 50)
      } else {
        downloads = Math.floor(300 * Math.exp(-age * 0.03) + Math.random() * 30)
      }
      buckets.push({
        bucketTime: d.toISOString(),
        updateId: uid,
        downloads: Math.max(5, downloads),
        uniqueDevices: Math.max(2, Math.floor(downloads * 0.6 + Math.random() * 10)),
      })
    }
  }
  return buckets
}

export const mockAdoption: AdoptionResponse = {
  timeseries: generateAdoptionTimeseries(),
  currentAdoption: [
    { updateId: 1, updateUuid: uuid(), runtimeVersion: '2.4.1', channel: 'production', branchName: 'main', deviceCount: 4230 },
    { updateId: 2, updateUuid: uuid(), runtimeVersion: '2.4.1', channel: 'production', branchName: 'main', deviceCount: 3180 },
    { updateId: 4, updateUuid: uuid(), runtimeVersion: '2.4.0', channel: 'production', branchName: 'main', deviceCount: 2850 },
    { updateId: 3, updateUuid: uuid(), runtimeVersion: '2.4.0', channel: 'production', branchName: 'main', deviceCount: 1920 },
    { updateId: 10, updateUuid: uuid(), runtimeVersion: '2.3.4', channel: 'production', branchName: 'main', deviceCount: 890 },
    { updateId: 8, updateUuid: uuid(), runtimeVersion: '2.3.7', channel: 'production', branchName: 'main', deviceCount: 502 },
    { updateId: 5, updateUuid: uuid(), runtimeVersion: '2.3.9', channel: 'canary', branchName: 'canary', deviceCount: 23 },
  ],
}

export const mockWebhooks: WebhookRecord[] = [
  {
    id: 1,
    url: 'https://hooks.slack.com/services/T00/B00/xxx',
    events: ['build.uploaded', 'build.published'],
    is_active: true,
    secret: null,
    created_at: daysAgo(10),
  },
  {
    id: 2,
    url: 'https://api.example.com/webhooks/ota',
    events: ['build.uploaded', 'build.published', 'update.created', 'update.patched'],
    is_active: false,
    secret: 'whsec_abc123',
    created_at: daysAgo(30),
  },
]
